# Generated by Django 2.2.6 on 2019-10-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_when_reply', models.IntegerField()),
                ('notify_when_comment', models.IntegerField()),
            ],
        )       
    ]
