# Generated by Django 2.2.6 on 2019-10-26 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
         migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=200, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('favorites', models.ManyToManyField(related_name='favorited_by', to='experiences.Experience')),
                ('settings', models.OneToOneField(blank=True, null=True, on_delete=models.CASCADE, to='accounts.Settings')),
                ('user', models.OneToOneField(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
