# Generated by Django 2.2.6 on 2019-10-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('accounts', '0002_auto_20191026_2259'),
    ]

    operations = [
    ]
