# Generated by Django 2.1.3 on 2019-10-21 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190821_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='settings',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Settings'),
        ),
    ]
