# Generated by Django 2.1.3 on 2019-10-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191021_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Settings'),
        ),
    ]
