# Generated by Django 2.2.6 on 2019-10-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
        ('accounts', '0006_auto_20191021_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='experiences.Experience'),
        ),
    ]
